# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("4chan.ch_frames", true);
user_pref("4chan.chan_frames", false);
user_pref("4chan.disable_all_page_features", false);
user_pref("4chan.enable_inline_post_expand", true);
user_pref("4chan.enable_post_expander", true);
user_pref("4chan.enable_quick_reply", true);
user_pref("4chan.enable_thread_watch", true);
user_pref("4chan.force_menu_background_colour", false);
user_pref("4chan.hidden_posts", "");
user_pref("4chan.hiddenboards", "");
user_pref("4chan.hide_closed_boards", false);
user_pref("4chan.hp_enable", false);
user_pref("4chan.ii_enable", true);
user_pref("4chan.ii_enable_spoiler", true);
user_pref("4chan.ii_last_shown_ad", 0);
user_pref("4chan.ii_limit_size", false);
user_pref("4chan.ii_max_height", 1000);
user_pref("4chan.ii_max_width", 1000);
user_pref("4chan.ii_width_newline_threshold", 500);
user_pref("4chan.last_run_version", "0.4.5.12");
user_pref("4chan.menu_background_colour", "white");
user_pref("4chan.nav_bottom_space", false);
user_pref("4chan.nav_enable", false);
user_pref("4chan.parser_max_replies", 100);
user_pref("4chan.parser_runtime_parsing", true);
user_pref("4chan.qr_close", true);
user_pref("4chan.qr_default_email", "");
user_pref("4chan.qr_default_username", "");
user_pref("4chan.qr_focus_after_quote", true);
user_pref("4chan.qr_inline", true);
user_pref("4chan.qr_quote_new_line", false);
user_pref("4chan.qr_show_quote", true);
user_pref("4chan.qr_show_quote_reply", false);
user_pref("4chan.reports_show_button", false);
user_pref("4chan.show_menu_bar", true);
user_pref("4chan.show_right_click", true);
user_pref("4chan.show_to_first_post_button", false);
user_pref("4chan.switch_menu_click_behaviour", false);
user_pref("4chan.tw_inline_pos_x", 10);
user_pref("4chan.tw_inline_pos_y", 40);
user_pref("4chan.tw_show_inline", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1273608729);
user_pref("app.update.lastUpdateTime.background-update-timer", 1273608452);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1273608586);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1273608483);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1273607145);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1273607149);
user_pref("browser.anchor_color", "#FFCCCC");
user_pref("browser.display.background_color", "#333333");
user_pref("browser.display.foreground_color", "#FFFFFF");
user_pref("browser.display.use_document_colors", false);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.lastDir", "/root/Desktop");
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://boards.4chan.org/g/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.3");
user_pref("browser.visited_color", "#99FFFF");
user_pref("extensions.enabledItems", "hidemenubar@moztw.org:3.6.20100218,{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}:1.0.8,{9AA46F4F-4DC7-4c06-97AF-5035170633FE}:0.4.5.12,{e4a8a97b-f2ed-450b-b12d-ee082ba24781}:0.8.20100408.6,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.3");
user_pref("extensions.lastAppVersion", "3.6.3");
user_pref("extensions.stylish.firstRun", 1);
user_pref("extensions.update.notifyUser", false);
user_pref("font.name.monospace.x-western", "GohuFont");
user_pref("font.name.sans-serif.x-western", "Calibri");
user_pref("font.name.serif.x-western", "Calibri");
user_pref("font.size.fixed.x-western", 9);
user_pref("general.autoScroll", true);
user_pref("greasemonkey.version", "0.8.20100408.6");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1276200962);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
